import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsEnum, IsOptional, IsNumber } from 'class-validator';

export class AddMessageDto {
  @ApiProperty({
    description: 'Role of the message sender',
    example: 'user',
    enum: ['user', 'assistant'],
  })
  @IsEnum(['user', 'assistant'])
  role!: string;

  @ApiProperty({
    description: 'Content of the message',
    example: 'Hello, how can I assist you today?',
  })
  @IsString()
  content!: string;

  @ApiProperty({
    description: 'Number of widgets generated by the message',
    example: 3,
    required: false,
  })
  @IsOptional()
  @IsNumber()
  widgetsGenerated?: number;
}
